baseURL = 'https://archibc.github.io/Blog/'
languageCode = 'zh-cn'
title = 'ArchiBC Blog'
theme = 'PaperMod'

[[menu.main]]
identifier = "search"
name = "搜索"
url = "search"
weight = 1

[[menu.main]]
identifier = "home"
name = "主页"
url = "/"
weight = 2

[[menu.main]]
identifier = "about"
name = "关于"
url = "posts"
weight = 3

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
author = "ArchiBC"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideFooter = false
ShowWordCounts = true
VisitCount = true
ShowLastMod = true
ShowToc = true
TocOpen = false
comments = true

[params.homeInfoParams]
Title = "Hi！"
Content = "这里是ArchiBC的保留地，日常分享的内容会放到这里。觉得有用可以给我打赏哦"

[[params.socialIcons]]
name = "bilibili"
url = "https://space.bilibili.com/199530139"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ArchiBC"

[[params.socialIcons]]
name = "kofi"
url = "https://ko-fi.com/archibc"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
